{{- $config := .Values.configData -}}
{{- $debugconfig := dict -}}
{{- $metricsconfig := dict -}}
{{- if .Values.metrics.enabled -}}
  {{- $debugconfig = mustMerge $config (fromJson "{ \"http\": { \"debug\": { \"addr\": \"0.0.0.0:5001\" } } }") -}}
  {{- if .Values.metrics.serviceMonitor.enabled -}}
    {{- $metricsconfig = mustMerge $debugconfig (fromJson (printf "{ \"http\": { \"debug\": { \"prometheus\": { \"enabled\": true, \"path\":\"%s\" } } } }" .Values.metrics.serviceMonitor.path ) ) -}}
  {{- end -}}
{{- end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "docker-registry.fullname" . }}-config
  labels:
    app: {{ template "docker-registry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.yml: |-
    {{- toYaml (coalesce $metricsconfig $debugconfig $config) | nindent 4 }}
